# Generated by Django 4.2 on 2026-01-29 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='PhysicalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('_base_price', models.DecimalField(db_column='base_price', decimal_places=2, max_digits=10)),
                ('_stock_quantity', models.IntegerField(db_column='stock_quantity', default=0)),
                ('product_type', models.CharField(choices=[('physical', 'Physical Product'), ('digital', 'Digital Product')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10)),
                ('dimensions', models.CharField(blank=True, help_text='Length x Width x Height', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_products', to='inventory_app.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('_base_price', models.DecimalField(db_column='base_price', decimal_places=2, max_digits=10)),
                ('_stock_quantity', models.IntegerField(db_column='stock_quantity', default=0)),
                ('product_type', models.CharField(choices=[('physical', 'Physical Product'), ('digital', 'Digital Product')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.CharField(help_text='File size in MB', max_length=100)),
                ('download_url', models.URLField()),
                ('license_type', models.CharField(choices=[('single', 'Single User'), ('team', 'Team License'), ('enterprise', 'Enterprise')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_products', to='inventory_app.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
